# -*- coding: utf-8 -*-
"""링크로본문가져오기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aoE0YbJjVflgOoEJbAEThopYnvlxu2-y
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import urllib.request
import seaborn as sns
from bs4 import BeautifulSoup
from nltk.tokenize import sent_tokenize

url = 'https://www.nytimes.com/2021/05/12/world/middleeast/israeli-palestinian-conflict-gaza-hamas.html?action=click&module=Spotlight&pgtype=Homepage'
html = urllib.request.urlopen(url)
soupNY = BeautifulSoup(html, 'html.parser')
print(soupNY.prettify())

soupNY.find_all('p',class_="css-axufdj evys1bk0")

main=''
for i in soupNY.find_all('p',class_="css-axufdj evys1bk0"):
  main+=i.get_text().strip()

main

main.replace("[^a-zA-Z#]", " ")

import nltk
nltk.download('punkt')
a=sent_tokenize(main)
a[10]

